### ISSUE TITLE
Bug is back: Popup saying that ignored files are in .gitignore

### ISSUE THREAD

**Issue by svenbergryen** [hsz/idea-gitignore#486]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Whenever I open a project, there's a message saying <<Ignored files found that are tracked: .ignore plugin found some files that are tracked with Git which are also listed in .gitignore file>>

### Steps to Reproduce

1. Open a PHPStorm project

**Expected behavior:** 
I expected the popup to appear only when appropriate and list the files that are tracked and in .gitignor

**Actual behavior:** 
Empty dialog opens.

**Reproduces how often:** 
Every time

### Versions

**Plugin:** 
2.2.2

**IDE:** 
PhpStorm 2017.3 EAP
Build #PS-173.3188.26, built on October 11, 2017
PhpStorm EAP User
Expiration date: November 10, 2017
JRE: 1.8.0_152-release-1024-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

**OS:** 
10.13.1

**Comment by svenbergryen** [comment]
This bug was recently fixed in https://github.com/hsz/idea-gitignore/issues/400

**Comment by kha1989led** [comment]
I'm getting that same behavior every time I open my project (which takes me to the empty dialog):
<img width="370" alt="screen shot 2017-10-18 at 10 41 11 am" src="https://user-images.githubusercontent.com/14830679/31733662-30e0b5aa-b3f1-11e7-809a-bce18fb1cc79.png">

Plugin version:
<img width="542" alt="screen shot 2017-10-18 at 10 40 30 am" src="https://user-images.githubusercontent.com/14830679/31733699-50d83018-b3f1-11e7-845a-89ff48ea27b6.png">

Intellij Idea version:
<img width="596" alt="screen shot 2017-10-18 at 10 41 40 am" src="https://user-images.githubusercontent.com/14830679/31733715-5d5355f2-b3f1-11e7-8fd8-280635c3f2bf.png">

**Comment by hsz** [comment]
@svenbergryen Thank you for this report. Issue was very weird and related to the IntelliJ API:
`ConcurrentWeakHashMap` map object was randomly cleared.

I've also changed the popup type from _warning_ to _information_.

**Comment by daneah** [comment]
@hsz I recently updated to `2.3.0` and still see this issue in PyCharm.

**Comment by hsz** [comment]
@daneah You mean that still empty dialog is displayed?

**Comment by daneah** [comment]
@hsz that's correct:

<img width="549" alt="screenshot 2017-11-06 11 10 08" src="https://user-images.githubusercontent.com/1808306/32454663-e5a71a28-c2ed-11e7-8799-19b58beb7456.png">

**Comment by pbienick** [comment]
Same here - it's coming up again for all of my projects. IDEA 2017.2.5, .ignore 2.3.0

**Comment by jpmschuler** [comment]
Confirmed, .ignore 2.3.0 PHPStorm 2017.2.4

**Comment by Jean85** [comment]
> Confirmed, .ignore 2.3.0 PHPStorm 2017.2.4
Same here

**Comment by daneah** [comment]
This bug still appears as of PyCharm 2018.1 and the latest version of this plugin.

**Comment by karfau** [comment]
Same here:

IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 3, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.68-1-MANJARO

![image](https://user-images.githubusercontent.com/135657/45570953-f4e9bf00-b864-11e8-8702-64814f658b73.png)

**Comment by borysboyko** [comment]
I am also seeing this issue.

**Comment by karfau** [comment]
I consider this bug a major thing, since the longer it is not fixed the more will people get used to ignoring this popup until it renders the plugin useless...
Is there anything we can do to support a fix for this?
I'm willing to spend money for getting this fixed.

**Comment by hsz** [comment]
This feature will be disabled with v3.1.0

**Comment by karfau** [comment]
I would love to understand your decision.

**Comment by hsz** [comment]
@karfau Sure, this popup was generating a false-positives in many cases and - as you mentioned - was ignored by the users. Annoying popup lead users to simply disable notifications.

In addition - triggering the git command `rm --cached --force {path}` may be a bit dangerous especially when `Project.getBaseDir` has been deprecated in IDE SDK (https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/project/Project.java#L44) - files location may be a bit different than expected (multiple modules).
